### PR TITLE
Enumerables

### PR DESCRIPTION
**Pull request by mohammadumar28**
This project is actually a clone of the project which I and my partner did. We had to change the main repository because my partner mistakenly added Stickler-ci Linter to the project. We could not remove it after trying many things. I am listing the original project's pull request link below.

https://github.com/Guy-Gustave/Custom-Enumerable-/pull/1

I am requesting for code review of this project.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
Status: requires changes
Hello Team,
You have done a nice job as some of the custom methods work as expected. But we need to make changes to remaining methods to ensure that they also work similarly to the default enumerable methods. 
**#my_each & #my_each_with_index**
when a block is given when self is a range returns the range itself after calling the given block once for each element in self

**#my_select**
returns an enumerator if no block is given

**#my_all?, #my_none?, #my_any?**
consider the following cases.

- when no block or argument is given

- when a class is passed as an argument 

- when a Regex is passed as an argument 

- when a pattern other than Regex or a Class is given returns 

**#my_map** 
when proc is given

**Comment by mohammadumar28** [comment]
Forgot to add this message in the commit: Modified the my_each and my_each_with_index to return Range when the self is Range.

**Comment by sumancrest0001** [comment]
**Status: Changes required 
Exceptional work TEAM :clap:** 
You have made significant improvements to your custom methods to make them behave like the default methods. We are very close to getting approval for this project. A little more effort is required to achieve the milestone.
Let's consider the following cases
**#my_none?**
when a pattern other than Regex or a Class is given 
when no block or argument is given 
**#my_map**
executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

**Comment by mohammadumar28** [comment]
> **Status: Changes required Exceptional work TEAM 👏**
> You have made significant improvements to your custom methods to make them behave like the default methods. We are very close to getting approval for this project. A little more effort is required to achieve the milestone.
> Let's consider the following cases
> **#my_none?**
> when a pattern other than Regex or a Class is given
> when no block or argument is given
> **#my_map**
> executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

I have modified the **my_none?** to run in the following case:

* When a pattern other than Regex or a Class is given
* When no block or argument is given

Also, modified **my_map** to execute on the Proc when both Block and Proc are given.

But when both Proc and block are passed into the original map method, it throws an error saying that both Proc and a block has been passed. 👇 

Screen Shot 2020-07-19 at 7 57 11 PM

**Comment by pelzolga123** [comment]
## Great work, congratulation :+1: Project Approved.
You did all changes required previously. 
Go ahead and merge to development.

_Goodluck in your next project._ *Happy coding*

**Pull request merged**
